### ISSUE TITLE
Using the locales tag

### ISSUE THREAD

**Issue by stuartcusackie** [edalzell/statamic-blade#75]
How would one go about outputting links to translated pages using the antlers locales tag?

I am trying to use the tag helper but this is producing an error for me:

```
@foreach (tag('locales') as $locale)
//
@endforeach
```

tag('locales') returns nothing. Neither does this:

`@dump(tag('locales', ['en']))`

**Comment by edalzell** [comment]
What error?

**Comment by stuartcusackie** [comment]
The foreach approach produces this error:
`foreach() argument must be of type array|object, string given`

This is because `tag('locales')` returns an empty string. The same goes for `tag('locales', ['en'])`

I also tried the tag helper from [this blog post](https://rias.be/blog/using-laravel-blade-with-statamic), but it's the same deal.

**Comment by dtorras** [comment]
@stuartcusackie did you find a solution? 

I've tried to define the context (as described in this PR https://github.com/edalzell/statamic-blade/pull/77), and it works on a simple Blade file. Statamic tries to find the data id on [this line](https://github.com/statamic/cms/blob/5dc32c03457ef50c4a0d91dee05fef27da9ffac6/src/Tags/Locales.php#L160), so you need to define the context with the id.

```tag('locales', [], collect(get_defined_vars())->except('__data', '__path')->toArray())```

But I'm trying to create a locale switcher on a Blade component used as app layout for navigation, and I can't get it to work because I can't get the context variables on the Blade component.

I guess I'll need to migrate from components to template inheritance for my layout.

**Comment by edalzell** [comment]
FYI, I'm hoping that 3.3 (coming out soon), makes this package unnecessary.

**Comment by stuartcusackie** [comment]
@dtorras I am afraid not. Instead I created a blade component called `LocaleLink`, which accepts the current entry id and the required locale name as a properties. The blade component then grabs the localised version of the current entry in it's constructor using these helpers that I wrote:

```
/**
   * Attempt to get the localised entry
   * if not fall back to origin.
   * 
   * @param $entryId integer
   * @param $locale string
   * @return Statamic\Entries\Entry
   */
    function entry_localised($entryId, $locale) {

        $origin = entry_origin($entryId);
        $descendants = $origin->descendants();

        return $descendants[$locale] ?? $origin;
        
    }

/**
  * Get the origin for an entry or 
  * fall back to self.
  * 
  * @param $entryId integer
  * @return Statamic\Entries\Entry
  */
  function entry_origin($entryId) {

    $entry = Entry::find($entryId);

    if($entry->hasOrigin()) {
      return $entry->origin();
    }
		
    return $entry;
}
```

**Comment by dtorras** [comment]
@stuartcusackie thanks! So you are using blade components? How do you grab the current entry on your blade component? I see Statamic variables are not available on the component.

> FYI, I'm hoping that 3.3 (coming out soon), makes this package unnecessary.

@edalzell I've already tried 3.3 beta, and I got the same result for the `locales` tag with `Statamic::tag()`. An empty string. I guess this issue exists on every tag depending on the context to fetch content. For this package #77 solves it. (if you are not working with Blade components).

**Comment by stuartcusackie** [comment]
@dtorras - I am passing the entry id to the component like so:
`<x-locale-link :entry-id="$page['id']" locale="ga">GA</x-locale-link>`

Then in the component constructor you I do this:

```
    public function __construct($entryId, $locale = 'en')
    {
        // See my helpers above:
        $this->localisedEntry = entry_localised($entryId, $locale);
        // Now you have the localised entry so you can generate links.
    }
```

**Comment by dtorras** [comment]
Thanks, @edalzell!

I will test it a bit more and then maybe submit the issue to the core repo because I'm unsure if the lack of default context is really an issue or the expected behaviour.

For now, following @stuartcusackie comment, I'm passing the entry ID on each Blade view. I don't really like it, but it works. 

To anyone who is in the same problem using Blade components, my temporal solution is:

```blade
<x-layouts.front entry-id="{{ $page->id }}">
    ...
</x-layouts.front>
```

The layout component:
```blade
<html>
<body>
    <nav>
        @foreach(Statamic::tag('locales')->context(['id' => $entryId]) as $locale)
            {{ $locale['permalink'] }}
        @endforeach
    </nav>
</body>
</html>
```

Or, using this package instead of Statamic 3.3:
```blade
<html>
<body>
    <nav>
        @foreach(tag('locales', [], ['id' => $pageId]) as $locale)
            {{ $locale['permalink'] }}
        @endforeach
    </nav>
</body>
</html>
```

**Comment by edalzell** [comment]
Please use native Statamic 3.3 tag [helper](https://statamic.dev/upgrade-guide/3-2-to-3-3#use-tags-in-blade), this addon will be archived.
